import Head from "next/head";
import { Inter } from "@next/font/google";
import { Navbar } from "../components/Navbar";
import { Main } from "../components/Main";
import { About } from "../components/About";
import { Skils } from "../components/Skils";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shanif Mohammed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skils />
      <Projects />
      <Contact />
    </div>
  );
}
